#!/bin/bash
mkdir tmp_eos_stuff
cd tmp_eos_stuff
curl -Lo eos.zip https://www.pabst-software.de/lib/exe/fetch.php?media=programme:eos:eos.zip
unzip eos.zip
cp -f EOS.exe /usr/bin/eos.exe
cd ..
rm -rf tmp_eos_stuff
cp -f eos /usr/bin/eos
