#!/bin/sh

# Parts of this script are stolen straight from oh-my-zsh:
# https://github.com/robbyrussell/oh-my-zsh

umask g-w,o-w

git clone -c core.eol=lf \
	-c fsck.zeroPaddedFilemode=ignore \
	-c fetch.fsck.zeroPaddedFilemode=ignore \
	-c receive.fsck.zeroPaddedFilemode=ignore \
	--depth=1 "https://github.com/robbyrussell/oh-my-zsh.git" \
        "~/.oh-my-zsh" \
        || { error "git clone of oh-my-zsh repo failed" ; exit 1 ; }

echo

cat <<-'EOF'
	         __                                     __
	  ____  / /_     ____ ___  __  __   ____  _____/ /_
	 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
	/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
	\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
	                        /____/                       ....is now installed!


	Please look over the ~/.zshrc file to select plugins, themes, and options.

	p.s. Follow us on https://twitter.com/ohmyzsh

	p.p.s. Get stickers, shirts, and coffee mugs at https://shop.planetargon.com/collections/oh-my-zsh

EOF
