#!/bin/sh

###### Make config directories
mkdir ~/.config
mkdir ~/.config/i3
mkdir ~/.config/vifm

###### Set configs
cp -f configs/i3/config ~/.config/i3/config
cp -f configs/i3/i3status ~/.config/i3/i3status
cp -f configs/i3/i3status1.sh ~/.config/i3/i3status1.sh
cp -f configs/i3/i3status2.sh ~/.config/i3/i3status2.sh
sudo cp -f configs/env /etc/environment
cp -f configs/vifmrc ~/.config/vifm/vifmrc
cp -f configs/gtk ~/.config/gtk-3.0/settings.ini

###### Install vim plugins
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim
git clone https://github.com/w0rp/ale ~/.vim/bundle/ale
cp -f configs/vimrc ~/.vimrc
git clone https://github.com/Valloric/YouCompleteMe.git ~/.vim/bundle/YouCompleteMe
ret=$(pwd)
cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
./install.py --clang-completer --cs-completer --java-completer --go-completer --rust-completer
cd $ret

###### Install Oh-my-zsh
tools/netsh 'https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh'
cp -f configs/zshrc ~/.zshrc

###### Configure git
RET=$(pwd)
cd /usr/share/doc/git/contrib/credential/gnome-keyring
sudo make
cd $RET
git config --global credential.helper /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
git config --global core.editor vim
git config --global commit.gpgsign true

###### X keyboard
cp configs/xinitrc $HOME/.xinitrc
cp configs/Xmodmap $HOME/.Xmodmap

###### Change the login shell to zsh
chsh -s /bin/zsh
