#!/bin/bash

source i3brc

###### Set configs
cd configs
make install
cd ..

###### Install fonts
packages/fonts

###### Install vim plugins
packages/vim

###### Install i3b-zsh
cp -f configs/zshrc ~/.zshrc
cp -f configs/zsh-theme ~/.zshtheme

###### Configure git
git config --global core.editor vim
modules/gitpg "$I3B_EMAIL"

###### Install wallpapers
git clone https://github.com/chrissxyt/walls ~/.walls
