#!/bin/bash

source i3brc

###### Set configs
cd configs
make install
cd ..

###### Install fonts
packages/fonts

###### Install vim plugins
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim
git clone https://github.com/w0rp/ale ~/.vim/bundle/ale
git clone https://github.com/Valloric/YouCompleteMe.git ~/.vim/bundle/YouCompleteMe
git clone https://github.com/tweekmonster/gofmt.vim.git ~/.vim/bundle/gofmt.vim
ret=$(pwd)
cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
./install.py $I3B_YCM_FLAGS
cd $ret

###### Install i3b-zsh
cp -f configs/zshrc ~/.zshrc
cp -f configs/zsh-theme ~/.zshtheme

###### Configure git
git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
git config --global core.editor vim
git config --global commit.gpgsign true

###### Install wallpapers
git clone https://github.com/chrissxyt/walls ~/.walls
