#!/bin/bash
# can be b, f, c or o
I3B_BROWSER=brave-browser
I3B_YED=0
I3B_EOS=0
I3B_BLUEJ=0
I3B_ARDUINO=1
I3B_TEENSY=1
I3B_TEAMVIEWER=1
I3B_FLASHPRINT=0
I3B_VSCODE=0
I3B_FL=0
I3B_GAMIX=0
I3B_NAS=""
I3B_SOURCES="default"
I3B_GHIDRA=0
I3B_DISCORD=0
I3B_TERM=kitty
I3B_YCM_FLAGS="--clang-completer --cs-completer --java-completer --go-completer --rust-completer"
if [ -f "/home/$(logname)/.i3brc" ] ; then
        source "/home/$(logname)/.i3brc"
fi
