#!/bin/sh

###### Update packages and add yubico repo
add-apt-repository ppa:yubico/stable
apt update
apt upgrade -y

###### Install main apps, drivers and dependencies
apt install -y ubuntu-drivers-common ubuntu-restricted-extras\
	ttf-ubuntu-font-family openssh-client curl gcc g++\
	libstartup-notification0 clang evince evince-common\
	make autoconf automake x11-xserver-utils arandr pavucontrol\
	python-gconf libpng-dev libusb-dev lxappearance\
	policykit-desktop-privileges policykit-1-gnome vim thunar\
	gnome-system-tools network-manager wireless-tools\
	overlay-scrollbar overlay-scrollbar-gtk2\
	totem-plugins gromit exfat-fuse exfat-utils\
	gstreamer1.0-pulseaudio transmission-gtk pulseaudio-utils\
	feh rofi compton gnome-terminal i3 i3-wm i3blocks\
	i3status xserver-xorg-video-intel hplip acpi-support\
	apport-gtk foomatic-db-compressed-ppds evince evince-common\
	libssh-4 libnm-glib-vpn1 dmz-cursor-theme libwayland-cursor0\
	libxcursor1 xcursor-themes mousetweaks laptop-detect\
	update-inetd update-notifier update-notifier-common\
	usb-creator-common usb-creator-gtk gnome-power-manager\
	libgsettings-qt1 libproxy1-plugin-gsettings\
	libappindicator3-1 gir1.2-appindicator3-0.1 gdebi\
	openjdk-8-jdk apt-transport-https fonts-hack-ttf curl
snap install vscode --classic
curl -L -o pmp.deb https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
dpkg -i pmp.deb
rm -f pmp.deb
add-apt-repository universe
dpkg --add-architecture i386
#curl -L -o whq.key https://dl.winehq.org/wine-builds/winehq.key
#apt-key add whq.key
#rm whq.key
curl -L -o - https://github.com/chrissxYT/winstallhq/raw/master/winstall.hq | sh
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
apt update
apt install -y dotnet-sdk-2.2 zsh htop tmux dosbox blender w3m\
	progress ncdu icdiff kdenlive mplayer obs-studio gimp\
	audacity rdesktop tor lm-sensors gnome-screensaver wireshark\
	libudev-dev cmake fonts-powerline breeze help2man\
	libcurl4-openssl-dev libssl-dev flex bison libelf-dev gcc-avr\
	binutils-avr avr-libc neofetch yubikey-manager-qt\
	yubikey-personalization-gui yubioath-desktop thunderbird\
	samba mono-complete p7zip-full iostat iotop dstat atop lz4\
	lzma net-tools libxft-dev libgtk2.0-dev libgtk-3-dev\
	webkit2gtk-4.0
# just to make sure icons arent corrupted all the time (happend on my machine)
apt remove -y breeze-cursor-theme

# Config the icons and themes and stuff
lxappearance

###### Get and install the Arduino IDE
curl -L -o ad.tar.xz "https://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz"
tar xJf ad.tar.xz
mv arduino-1.8.8 /usr/bin/
cd /usr/bin/arduino-1.8.8
./arduino-linux-setup.sh $USER
popd
rm -f ad.tar.xz

###### Get and install the Teensy loader
curl -L -o /etc/udev/rules.d/49-teensy.rules "https://www.pjrc.com/teensy/49-teensy.rules"
curl -L -o t.tar.gz "https://www.pjrc.com/teensy/teensy_linux64.tar.gz"
tar xzf t.tar.gz
mv teensy /bin
rm -f t.tar.gz libpng12.so.0 libusb-0.1.so.4

###### Get and install Teensyduino
curl -L -o td "https://www.pjrc.com/teensy/td_145/TeensyduinoInstall.linux64"
chmod +x td
./td

###### Get and install TeamViewer
curl -L -o tv.deb 'https://download.teamviewer.com/download/linux/teamviewer_amd64.deb'
dpkg -i tv.deb
rm -f tv.deb

###### Get and install ybacklight
curl -L -o yb.sh "https://github.com/chrissxYT/ybacklight/raw/master/installer.sh"
chmod +x yb.sh
./yb.sh
rm -f yb.sh

###### Get and install FlashPrint
curl -L -o fp.deb 'http://www.sz3dp.com/upfile/2018/12/03/20181203162713_662.deb'
dpkg -i fp.deb
rm -f fp.deb

###### Get and install playerctl
curl -L -o pc.deb 'https://github.com/acrisci/playerctl/releases/download/v2.0.1/playerctl-2.0.1_amd64.deb'
dpkg -i pc.deb
rm -f pc.deb

###### Get and install Chrome
curl -L -o ch.deb 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
dpkg -i ch.deb
rm -f ch.deb

###### Make config directories
mkdir ~/.config
mkdir ~/.config/i3

###### Set configs
cp -f configs/i3/config ~/.config/i3/config
cp -f configs/i3/i3status ~/.config/i3/i3status
cp -f configs/env /etc/environment

###### Install vim plugins
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim
git clone https://github.com/w0rp/ale ~/.vim/bundle/ale
git clone https://github.com/scrooloose/nerdtree ~/.vim/bundle/nerdtree
git clone https://github.com/Xuyuanp/nerdtree-git-plugin ~/.vim/bundle/nerdtree-git-plugin
cp -f configs/vimrc ~/.vimrc

###### Install Oh-my-zsh
curl -L -o omz.sh 'https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh'
chmod +x omz.sh
./omz.sh
cp -f configs/zshrc ~/.zshrc
rm -f omz.sh

###### Remove bloatware
apt remove -y firefox gedit
#apt remove -y gnome-bluetooth
#apt remove -y gnome-accessibility-themes
apt remove -y gnome-user-docs gnome-user-guide
#apt remove -y gnome-disk-utility
#apt remove -y gnome-software
snap remove gnome-calculator
#snap remove gnome-system-monitor
#snap remove gnome-characters

###### Install helper "scripts"
cp -f tools/ghk /bin/ghk
cp -f tools/ghp /bin/ghp
cp -f tools/update /bin/update
cp -f tools/mnt /bin/mnt
cp -f tools/unmount /bin/unmount
vim ghk.txt
openssl aes-256-cbc -a -in ghk.txt -out ~/.ghk.enc
rm -f ghk.txt

###### Change the login shell to zsh
chsh -s /bin/zsh

###### Finish up everything
apt --fix-broken install
apt autoremove
update

###### Reboot the system
shutdown -r now
