#!/bin/bash

fixme() (echo -e "----------\n\n\n\n\n\n
fixme: Installing $1 package(s)/module \"$2\" failed.
\n\n\n\n\n\n----------")

isnap() (echo "Installing snap \"$1\"..." ; snap install $@ || fixme snap "$1")
iapt()  (apt install -y $@ || fixme apt "$@")
ipip()  (pip install $@ || fixme pip "$@")
ipip3() (pip3 install $@ || fixme pip3 "$@")
imod()  (source "modules/$1" || fixme i3buntu "$1")
insh()  (netsh $@ || fixme netsh "$@")

apt_update() (rm -rf /etc/apt/sources.list.d ; apt update)

source urls
source i3brc

# install sources.list
cp -f configs/sources.list /etc/apt/sources.list
sed "s/%PROXY%/$(echo "$I3B_APT_CACHE" | sed 's/\//\\\//')/"
dpkg --add-architecture i386
apt-key add packages/keys.gpg
apt_update

###### Install tools before doing anything else (i also put wicd in
###### here, because it is one of the few things requiring user
###### interaction)
iapt wicd
iapt curl gcc make
cd tools
make install clean
cd ..

###### Update
apt upgrade -y
apt autoremove -y

###### Install main apps, drivers and dependencies
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
iapt g++ clang
[ "$I3B_VSCODE" = 1 ] && isnap vscode --classic
isnap github-desktop --beta --classic
cp -f configs/env /etc/environment
for p in $(cat packages/apt) ; do iapt $p ; done
for p in $(cat packages/pip) ; do ipip $p ; done
for p in $(cat packages/pip3) ; do ipip3 $p ; done
packages/netsh || fixme netsh "any of the general ones"
likeu -l
[[ "$I3B_BROWSER" == *"brave"* ]] && iapt brave-browser
[[ "$I3B_BROWSER" == *"opera"* ]] && iapt opera-stable
[[ "$I3B_BROWSER" == *"firefox"* ]] && iapt firefox
[[ "$I3B_BROWSER" == *"chrome"* ]] && iapt google-chrome-stable

###### set the cursor to something making sense
rm -f /etc/alternatives/x-cursor-theme
ln -s /usr/share/icons/DMZ-White/cursor.theme /etc/alternatives/x-cursor-theme

###### disable "Natural Scrolling" because it is UNNATURAL AS FUCK
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false

###### Get and install yEd
[ "$I3B_YED" = 1 ] && insh "$I3B_YED_DL_URL"

###### Get and install BlueJ
[ "$I3B_BLUEJ" = 1 ] && udpkg "$I3B_BLUEJ_DL_URL"

###### Get and install the Arduino IDE
[ "$I3B_ARDUINO" = 1 ] && imod arduino

###### Get and install the Teensy loader
[ "$I3B_TEENSY" = 1 ] && imod teensy

###### Get and install Teensyduino
[ "$I3B_ARDUINO" = 1 && "$I3B_TEENSY" = 1 ] && insh "$I3B_TEENSYDUINO_DL_URL"

###### Get and install Ghidra
[ "$I3B_GHIDRA" = 1 ] && imod ghidra

###### Get and install TeamViewer
[ "$I3B_TEAMVIEWER" = 1 ] && iapt teamviewer

###### Get and install FlashPrint
[ "$I3B_FLASHPRINT" = 1 ] && udpkg "$I3B_FLASHPRINT_DL_URL"

###### Run Gamix
[ "$I3B_GAMIX" = 1 ] && insh -C "./gamix.sh ns" -c chrissxYT/gamix

###### Install FL Studio
[ "$I3B_FL" = 1 ] && imod fl

###### Install Discord
[ "$I3B_DISCORD" = 1 ] && udpkg "$I3B_DISCORD_DL_URL"

###### Build git libsecret cred helper
imod gitsecret

###### Get and install rofi-calc
imod rofi-calc

###### Get and install EOS
[ "$I3B_EOS" = 1 ] && imod eos

###### Change the distro name
cp -f configs/issue /etc/issue
cp -f configs/issue.net /etc/issue.net
cp -f configs/os-release /etc/os-release
cp -f configs/lsbr /etc/lsb-release

###### Set the locales
cp configs/locale /etc/default/locale

###### Finish up everything
apt_update
apt -f install -y
apt autoremove -y

###### Install the NAS
echo "$I3B_NAS" >> /etc/fstab

# give the user rights to all of their home directory
chown -R "$(logname):$(logname)" ~

# change the login shell to zsh
# (have to do this here, so you dont have to put in your pw again)
chsh -s /bin/zsh "$(logname)"
