#!/bin/bash

###### Update packages and add ppas
add-apt-repository -y ppa:yubico/stable
add-apt-repository -y ppa:nextcloud-devs/client
apt update
apt upgrade -y

###### Install main apps, drivers and dependencies
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
apt install -y curl gcc g++ clang make
[ $7 = 1 ] && snap install vscode --classic
snap install github-desktop --beta --classic
curl -L -o pmp.deb https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
dpkg -i pmp.deb
rm -f pmp.deb
add-apt-repository -y universe
dpkg --add-architecture i386
tools/netsh chrissxYT/winstallhq
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
apt-add-repository -y \
        "deb https://download.mono-project.com/repo/ubuntu preview main"
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository -y \
   "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | apt-key add -
add-apt-repository -y \
        "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ disco main"
apt update
for p in $(cat apt) ; do apt install -y $p ; done
for p in $(cat pip) ; do pip install $p ; done
[ "$1" = "b" ] && apt install -y brave-browser
[ "$1" = "o" ] && tools/tools/udpkg "https://download1.operacdn.com/pub/opera/desktop/60.0.3255.109/linux/opera-stable_60.0.3255.109_amd64.deb"
[ "$1" = "f" ] && apt install -y firefox
[ "$1" = "c" ] && tools/tools/udpkg 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
# just to make sure icons arent corrupted all the time (happend on my machine)
apt remove -y breeze-cursor-theme

###### Install slmenu
hg clone https://bitbucket.org/rafaelgg/slmenu
cd slmenu
make install clean
cd ..
rm -rf slmenu

###### Get and install imlib2-heic (HEIC for feh)
git clone https://github.com/vi/imlib2-heic.git im2heic
cd im2heic
make
make install
cd ..
rm -rf im2heic

###### Get and install yEd
if [[ $2 -eq 1 ]]
then
	curl -L -o yed.sh "https://www.yworks.com/resources/yed/demo/yEd-3.19_with-JRE11_64-bit_setup.sh"
	chmod +x yed.sh
	./yed.sh
	rm -f yed.sh
fi

###### Get and install fzf
tools/udpkg http://launchpadlibrarian.net/405439988/fzf_0.17.5-2_amd64.deb

###### Get and install sane-sent
curl -L -o ss.zip https://github.com/chrissxYT/sane-sent/archive/c001.zip
unzip ss.zip
cd sane-sent-c001
make install
cd ..
rm -rf sane-sent-c001
rm -f ss.zip

###### Get and install the Arduino IDE
if [[ $3 -eq 1 ]]
then
	curl -L "https://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz" |\
                tar xJf -
	mv arduino-1.8.8 /usr/bin/
	ret=$(pwd)
	cd /usr/bin/arduino-1.8.8
	./arduino-linux-setup.sh $USER
	cd $ret
fi

if [[ $4 -eq 1 ]]
then
	###### Get and install the Teensy loader
	curl -L -o /etc/udev/rules.d/49-teensy.rules "https://www.pjrc.com/teensy/49-teensy.rules"
	curl -L -o t.tar.gz "https://www.pjrc.com/teensy/teensy_linux64.tar.gz"
	tar xzf t.tar.gz
	mv -f teensy /usr/bin
	rm -f t.tar.gz libpng12.so.0 libusb-0.1.so.4
	
	###### Get and install Teensyduino
	curl -L -o td "https://www.pjrc.com/teensy/td_145/TeensyduinoInstall.linux64"
	chmod +x td
	./td
	rm -f td
fi

###### Get and install TeamViewer
[ $5 -eq 1 ] && tools/udpkg 'https://download.teamviewer.com/download/linux/teamviewer_amd64.deb'

###### Get and install ybacklight
tools/netsh -c chrissxYT/ybacklight

###### Get and install FlashPrint
[ $6 -eq 1 ] && tools/udpkg 'http://www.sz3dp.com/upfile/2018/12/03/20181203162713_662.deb'

###### Get and install playerctl
tools/udpkg 'https://github.com/acrisci/playerctl/releases/download/v2.0.1/playerctl-2.0.1_amd64.deb'

###### Get and install the master branch of neofetch
###### (the packaged versions don't have the i3buntu fix yet)
git clone https://github.com/dylanaraps/neofetch.git nf
cd nf
make install
cd ..
rm -rf nf

###### Get and install EOS
if [[ $2 -eq "1" ]] ; then
	mkdir tmp_eos_stuff
	cd tmp_eos_stuff
	curl -L -o eos.zip "https://www.pabst-software.de/lib/exe/fetch.php?media=programme:eos:eos.zip"
	unzip eos.zip
	cp -f EOS.exe /usr/bin/eos.exe
	cd ..
	rm -rf tmp_eos_stuff
        cp -f tools/eos /usr/bin/eos
fi

###### Install tools
cp -f tools/update /usr/bin/update
cp -f tools/_update /usr/bin/_update
cp -f tools/mnt /bin/mnt
cp -f tools/umnt /bin/umnt
cp -f tools/netsh /usr/bin/netsh
cp -f tools/lock /usr/bin/lock
cp -f tools/udpkg /usr/bin/udpkg
cp -f tools/screenshot /usr/bin/screenshot
cp -f tools/todo /usr/bin/todo
tools/netsh -c chrissxYT/likeu

###### Change the distro name
cp -f configs/issue /etc/issue
cp -f configs/issue.net /etc/issue.net
cp -f configs/os-release /etc/os-release
cp -f configs/lsbr /etc/lsb-release

###### Finish up everything
apt -f install -y
apt autoremove -y

# give the user rights to all of their home directory
chown -R $8:$8 ~
