#!/bin/sh
{
        sudo apt update
        sudo apt install -y git
        git clone https://github.com/chrissxYT/i3buntu.git .i3buntu
        cd .i3buntu
        sudo ./install | sed 's/^WARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n//'
        ./config
        cd ..
        echo 'Restarting...'
        shutdown -r now
} | tee -a ~/.i3buntu.log
