#!/bin/sh
sudo apt update
sudo apt install -y git
git clone https://github.com/chrissxYT/i3buntu.git .i3buntu
cd .i3buntu
sudo ./install
./config
cd ..
echo -n 'Restarting in 10...'
for i in 10 9 8 7 6 5 4 3 2 1 ; do
        echo -n "$i..."
        sleep 1
done
echo
sudo shutdown -r now
