#!/bin/sh
git pull
cd tools
sudo make install clean
cd ../packages
sudo make install
cd ../configs
make update
cd ..
[ ! -d "~/.walls" ] && git clone https://github.com/chrissxyt/walls ~/.walls
update
