cp:
	cp -f ~/.vimrc vimrc
	cp -f ~/.zshrc zshrc
	cp -f ~/.xinitrc xinitrc
	cp -f ~/.Xmodmap Xmodmap
	cp -f /etc/environment env
	cp -f ~/.config/vifm/vifmrc vifmrc
	cp -f ~/.config/gtk-3.0/settings.ini gtk
	cp -f /etc/issue issue
	cp -f /etc/issue.net issue.net
	cp -f /etc/lsb-release lsbr
	cp -f /etc/os-release os-release
	@cd i3 && make cp
