execute pathogen#infect()
syntax on
filetype plugin indent on
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ }
autocmd BufWritePost *.c,*.h,*.cc,*.hh,*.cpp,*.hpp if filereadable("Makefile") | !make test
autocmd BufWritePost slides !sent %

" map <C-c> "+y
" map <C-v> "+P
