let mapleader = " "
execute pathogen#infect()
syntax on
filetype plugin indent on
set laststatus=2
set nocompatible
set number
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set mouse=a
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ }
autocmd BufWritePost *.c,*.h,*.cc,*.hh,*.cpp,*.hpp if filereadable("Makefile") | !make test
autocmd BufWritePost slides !sent %
autocmd BufWritePost slides.md !md2pdf % $(echo % | sed s/.md/.pdf/) && mupdf $(echo % | sed s/.md/.pdf/)
autocmd BufWritePost .vimrc source %

map <Leader>c "+y
map <Leader>v "+P
