execute pathogen#infect()
syntax on
filetype plugin indent on
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ }
autocmd StdinReadPre * let s:std_in=1
autocmd BufWritePost config.h !sudo make install
