export ZSH="/home/$USER/.oh-my-zsh"
ZSH_THEME="agnoster"
export UPDATE_ZSH_DAYS=7

DISABLE_UPDATE_PROMPT="true"
#DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="false"
HIST_STAMPS="dd.mm.yyyy"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git encode64 extract z)

source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
export EDITOR='vim'
export ARCHFLAGS="-arch x86_64"
export TERM=xterm-256color

zlibd() (printf "\x1f\x8b\x08\x00\x00\x00\x00\x00"|cat - $@|gzip -dc)
v()     ($EDITOR $@)
e()     ($EDITOR $(ls | fzf))
uzip()  (unzip -d "$(echo $1 | sed s/\.zip//g -)" "$1")
sd()    (sudo shutdown now)

xmodmap -e "clear lock"
xmodmap -e "keycode 66 = Escape"
#xmodmap -e "keycode 47 = parenleft braceleft"
#xmodmap -e "keycode 48 = parenright braceright"
#xmodmap -e "keycode 34 = slash bar"
#xmodmap -e "keycode 20 = backslash question"
#xmodmap -e "keycode 135 = Multi_key"

# hard mode
#xmodmap -e "keycode 9  = NoSymbol"
#xmodmap -e "keycode 16 = 7 NoSymbol 7 NoSymbol NoSymbol seveneighths NoSymbol"
#xmodmap -e "keycode 17 = 8 NoSymbol 8 NoSymbol bracketleft trademark bracketleft"
#xmodmap -e "keycode 18 = 9 NoSymbol 9 NoSymbol bracketright plusminus bracketright"
#xmodmap -e "keycode 19 = 0 equal 0 equal NoSymbol degree NoSymbol"
#xmodmap -e "keycode 94 = less greater less greater NoSymbol dead_belowmacron NoSymbol dead_belowmacron less greater NoSymbol dead_belowmacron"

neofetch
