#!/bin/bash

# SECURITY NOTE:
# Please make sure that top, iwconfig and ifconfig cannot be altered
# by bad people, because they could possibly cause damage.

# segment text color
segment() {
        echo -n "{\"name\":\"\",\"color\":\"$2\",\"full_text\":\"$1\",\"separator\":false,\"separator_block_width\":0}"
}

diskspace() {
        segment "$(df -h --output=avail / | grep -v Avail | sed 's/ //g')iB free " "#FFFFFF"
}

wifi() {
        iwconfig="$(iwconfig 2>/dev/null)"
        essid="$(echo "$iwconfig" | grep ESSID: | sed 's/.*ESSID:\"\(.*\)\".*/\1/')"
        rate="$(echo "$iwconfig" | grep "Bit Rate" | sed 's/.*Bit Rate=\(.* .b\/s\).*/\1/' | sed 's/ \(.\)b\/s/\1/')"
        quality="$(echo "$(echo "$iwconfig" | grep "Link Quality" | sed 's/.*Link Quality=\([0-9]*\/[0-9]*\) .*/\1/')*100" | bc -sql | cut -c1-3 | sed 's/\.\?$/%/')"
        freq="$(echo "$iwconfig" | grep Frequency: | sed 's/.*Frequency:\([0-9]*\).*/\1/')"
        [[ "$freq" == 2 ]] && freq="2.4"
        freq="$freq GHz"
        [[ "$essid" != "Gratis-Viren Google Wifi Edition" ]] && essid="📶 $essid" || essid="🏠"
        segment " $essid ($quality, $rate, $freq) " "#00FF00"
}

battery() {
        acpi="$(acpi -b | sed s/,//g)"
        status="$(echo "$acpi" | cut -d' ' -f3)"
        percentage="$(echo "$acpi" | cut -d' ' -f4)"
        remaining="$(echo "$acpi" | cut -d' ' -f5)"
        if [[ $percentage == *"100%"* ]] ; then
                status=🔌
	elif [[ $status == *"Discharging"* ]] ; then
		status=🔋
	elif [[ $status == *"Charging"* && $percentage != *"100%"* ]] ; then
                status=⚡
        else
                status=❔
	fi
        segment " $status $percentage $remaining " "#FFFFFF"
}

temp() {
        segment " $(acpi -t | cut -d' ' -f4 | cut -d. -f1)°C " "#FFFFFF"
}

cpu() {
        segment " $(echo "100-$(top -bn1 | grep '^%Cpu(s):' | sed 's/%Cpu(s): [ 0-9.]* us, [ 0-9.]* sy, [ 0-9.]* ni, \([ 0-9.]*\) id, [ 0-9.]* wa, [ 0-9.]* hi, [ 0-9.]* si, [ 0-9.]* st/\1/')" | bc -sql | cut -c1-3 | sed 's/\.\?$/%/') " "#FFFFFF"
}

audio() {
        amixer sget Master | grep off >/dev/null \
                && \
                        segment " 🔇 " "#FFFFFF" \
                || \
                        segment " 🔉 $(pactl list sinks | grep "Volume: " | grep -v "Base Volume:" | sed 's/.* \([0-9]\+%\).*/\1/') " "#FFFFFF"
}

datetime() {
        segment " $(date "+%d.%m.%Y %T") " "#FFFFFF"
}

backlight() {
        segment " 💻 $(ybacklight Sc/Sm)" "#FFFFFF"
}

separator() {
        segment "" "#FFFFFF"
}

render() {
        echo -n '['
        diskspace
        echo -n ','
        separator
        echo -n ','
        wifi
        echo -n ','
        separator
        echo -n ','
        battery
        echo -n ','
        separator
        echo -n ','
        temp
        echo -n ','
        separator
        echo -n ','
        cpu
        echo -n ','
        separator
        echo -n ','
        audio
        echo -n ','
        separator
        echo -n ','
        datetime
        echo -n ','
        separator
        echo -n ','
        backlight
        echo '],'
}

main() {
        echo '{"version":1}'
        echo '['
        while true ; do
                render
                sleep 0.5
        done
}

main
