cp:
	cp -f ~/.config/i3/config config
	cp -f ~/.config/i3/i3status.sh i3status.sh
	cp -f ~/.config/i3/i3status i3status
	cp -f ~/.config/i3/i3bstatus i3bstatus

install:
	mkdir -p ~/.config/i3
	cp -f config ~/.config/i3/config
	cp -f i3status.sh ~/.config/i3/i3status.sh
	cp -f i3status ~/.config/i3/i3status
	cp -f i3bstatus ~/.config/i3/i3bstatus

update: install
