cp:
	cp -f ~/.config/i3/config config
	cp -f ~/.config/i3/i3status.sh i3status.sh
	cp -f ~/.config/i3/i3status i3status

install:
	cp -f config ~/.config/i3/config
	cp -f i3status.sh ~/.config/i3/i3status.sh
	cp -f i3status ~/.config/i3/i3status
