cp:
	cp -f ~/.config/i3/config config
	cp -f ~/.config/i3/disk.c disk.c
	cp -f ~/.config/i3/i3bstatus i3bstatus
	cp -f ~/.config/i3/i3block i3block

install:
	mkdir -p ~/.config/i3
	cp -f config ~/.config/i3/config
	cp -f disk.c ~/.config/i3/disk.c
	cp -f i3bstatus ~/.config/i3/i3bstatus
	cp -f i3block ~/.config/i3/i3block

update: install
