#!/bin/sh
FILE="$HOME/ncl/bookmarks"

echo "" >> "$FILE"

[ "$1" = "f" ] && \
        cat "$FILE" | \
        dmenu -l 20 | \
        xclip -in -selection clipboard \
|| \
        xclip -out -selection clipboard >> "$FILE"

echo "" >> "$FILE"
